export type Lang = "en" | "es"

export const V2_STRINGS = {
  en: {
    // shared
    brand: "Samwise",
    backHome: "Home",
    loading: "Loading…",
    save: "Save",
    saving: "Saving…",
    saved: "Saved",
    cancel: "Cancel",
    delete: "Delete",
    add: "Add",
    edit: "Edit",
    logout: "Log out",

    // login
    loginTitle: "Welcome back.",
    loginSub: "Sign in to manage your calls.",
    loginCta: "Sign in",
    loginBusy: "Signing in…",
    noAccount: "No account yet?",
    goSignup: "Create one free",

    // signup
    signupTitle: "Start free.",
    signupSub: "Two minutes. No card. Your first call can be tomorrow morning.",
    signupCta: "Create my account",
    signupBusy: "Creating your account…",
    haveAccount: "Already have an account?",
    goLogin: "Sign in",

    // fields
    name: "Name",
    namePh: "Your name",
    phone: "Phone",
    phoneHelp: "International format — this is the number we call.",
    email: "Email",
    password: "Password",
    passwordHelp: "At least 8 characters.",
    timezone: "Timezone",
    timezoneHelp: "Your call times are read in this zone.",
    firstCall: "First call time",
    firstCallHelp: "Optional — you can add more times later.",
    tzSearch: "Search timezones…",
    tzNoResults: "No timezone matches that.",

    // settings
    settingsTitle: "Your settings",
    profileHeading: "Profile",
    profileSub: "Name, number, and the zone your call times are read in.",
    schedulesHeading: "Call times",
    schedulesSub: "We call you at these times, in your own timezone. Add as many as you need.",
    schedulesEmpty: "No call times yet. Add your first one below.",
    addTimeLabel: "New time",
    activeOn: "Active",
    activeOff: "Paused",
    toggleToPause: "Pause this call",
    toggleToResume: "Resume this call",
    confirmDelete: "Delete this call time?",

    callLanguage: "Call language",
    callLanguageHelpUser: "The language the voice agent speaks when it calls you. Separate from the language of this page.",
    callLanguageHelpContact: "The language we speak when we call them.",
    langEs: "Spanish",
    langEn: "English",
    langHe: "Hebrew",
    agentSoonTitle: "Agent coming soon",
    agentSoonBody:
      "We don't have a voice agent in {language} yet. We're creating one — it will be ready within 24 hours, and calls in this language will begin automatically once it's live.",
    agentSoonContacts: "These support contacts are waiting on a voice agent:",

    contactsHeading: "Support contacts",
    contactsSub:
      "People we may phone if you miss your calls or the call hears you struggling. You will not receive this call — we reach out to them. Add people you actually trust to pick up.",
    contactsEmpty: "No support contacts yet. Add the first person below.",
    contactName: "Name",
    contactNamePh: "Their name",
    contactPhone: "Phone",
    contactRelationship: "Relationship",
    contactRelationshipPh: "friend, family, coach…",
    contactRelationshipHelp: "Optional — just for your own reference.",
    contactEmail: "Email (optional)",
    contactEmailPh: "name@example.com",
    contactEmailHelp: "If they don't answer Samwise's call, we'll send them a short email instead.",
    contactEmailInvalid: "Enter a valid email, e.g. name@example.com",
    contactAdd: "Add contact",
    contactAddHeading: "Add a support contact",
    contactSave: "Save contact",
    contactPause: "Pause this contact",
    contactResume: "Resume this contact",
    contactConfirmDelete: "Remove this support contact?",
    contactNoRelationship: "—",

    historyHeading: "Recent calls",
    historySub: "The last 20 calls, newest first.",
    historyEmpty: "No calls yet. Your first one will show up here.",
    colWhen: "When",
    colResult: "Result",
    colStatus: "Status",
    colEnd: "End reason",
    colLatency: "Latency",
    colSummary: "Summary",
    success: "Connected",
    notSuccess: "Did not connect",
    score: "Score",
    sentiment: "Sentiment",
    goal: "Goal achieved",
    noSummary: "—",
    yes: "Yes",
    no: "No",
    callToYou: "Your call",
    callToContact: "Support call",
    callToContactNamed: "Support call to",

    genericError: "Something went wrong. Try again.",
  },

  es: {
    brand: "Samwise",
    backHome: "Inicio",
    loading: "Cargando…",
    save: "Guardar",
    saving: "Guardando…",
    saved: "Guardado",
    cancel: "Cancelar",
    delete: "Eliminar",
    add: "Agregar",
    edit: "Editar",
    logout: "Cerrar sesión",

    loginTitle: "Bienvenido de nuevo.",
    loginSub: "Entra para gestionar tus llamadas.",
    loginCta: "Entrar",
    loginBusy: "Entrando…",
    noAccount: "¿Aún no tienes cuenta?",
    goSignup: "Crea una gratis",

    signupTitle: "Empieza gratis.",
    signupSub: "Dos minutos. Sin tarjeta. Tu primera llamada puede ser mañana.",
    signupCta: "Crear mi cuenta",
    signupBusy: "Creando tu cuenta…",
    haveAccount: "¿Ya tienes cuenta?",
    goLogin: "Entrar",

    name: "Nombre",
    namePh: "Tu nombre",
    phone: "Teléfono",
    phoneHelp: "Formato internacional — a este número te llamamos.",
    email: "Correo",
    password: "Contraseña",
    passwordHelp: "Mínimo 8 caracteres.",
    timezone: "Zona horaria",
    timezoneHelp: "Tus horarios se leen en esta zona.",
    firstCall: "Hora de la primera llamada",
    firstCallHelp: "Opcional — puedes agregar más horarios después.",
    tzSearch: "Buscar zona horaria…",
    tzNoResults: "Ninguna zona coincide.",

    settingsTitle: "Tu configuración",
    profileHeading: "Perfil",
    profileSub: "Nombre, número y la zona en la que se leen tus horarios.",
    schedulesHeading: "Horarios de llamada",
    schedulesSub: "Te llamamos a estas horas, en tu propia zona horaria. Agrega las que necesites.",
    schedulesEmpty: "Aún no tienes horarios. Agrega el primero abajo.",
    addTimeLabel: "Nueva hora",
    activeOn: "Activa",
    activeOff: "En pausa",
    toggleToPause: "Pausar esta llamada",
    toggleToResume: "Reactivar esta llamada",
    confirmDelete: "¿Eliminar este horario?",

    callLanguage: "Idioma de la llamada",
    callLanguageHelpUser: "El idioma en que el agente de voz te habla cuando te llama. Es distinto del idioma de esta página.",
    callLanguageHelpContact: "El idioma en que les hablamos cuando los llamamos.",
    langEs: "Español",
    langEn: "Inglés",
    langHe: "Hebreo",
    agentSoonTitle: "Agente en camino",
    agentSoonBody:
      "Todavía no tenemos un agente de voz en {language}. Estamos creando uno — estará listo en menos de 24 horas, y las llamadas en este idioma comenzarán automáticamente cuando esté activo.",
    agentSoonContacts: "Estos contactos de apoyo están esperando un agente de voz:",

    contactsHeading: "Contactos de apoyo",
    contactsSub:
      "Personas a las que podemos llamar si pierdes tus llamadas o si la llamada nota que estás luchando. Tú no recibes esta llamada — los contactamos a ellos. Agrega personas en las que de verdad confíes para contestar.",
    contactsEmpty: "Aún no tienes contactos de apoyo. Agrega a la primera persona abajo.",
    contactName: "Nombre",
    contactNamePh: "Su nombre",
    contactPhone: "Teléfono",
    contactRelationship: "Relación",
    contactRelationshipPh: "amigo, familia, coach…",
    contactRelationshipHelp: "Opcional — solo para tu referencia.",
    contactEmail: "Correo (opcional)",
    contactEmailPh: "nombre@ejemplo.com",
    contactEmailHelp: "Si no contestan la llamada de Samwise, les enviaremos un correo corto en su lugar.",
    contactEmailInvalid: "Ingresa un correo válido, p. ej. nombre@ejemplo.com",
    contactAdd: "Agregar contacto",
    contactAddHeading: "Agregar un contacto de apoyo",
    contactSave: "Guardar contacto",
    contactPause: "Pausar este contacto",
    contactResume: "Reactivar este contacto",
    contactConfirmDelete: "¿Eliminar este contacto de apoyo?",
    contactNoRelationship: "—",

    historyHeading: "Llamadas recientes",
    historySub: "Las últimas 20 llamadas, de la más reciente a la más antigua.",
    historyEmpty: "Aún no hay llamadas. La primera aparecerá aquí.",
    colWhen: "Cuándo",
    colResult: "Resultado",
    colStatus: "Estado",
    colEnd: "Motivo de cierre",
    colLatency: "Latencia",
    colSummary: "Resumen",
    success: "Conectada",
    notSuccess: "No conectó",
    score: "Puntaje",
    sentiment: "Sentimiento",
    goal: "Objetivo logrado",
    noSummary: "—",
    yes: "Sí",
    no: "No",
    callToYou: "Tu llamada",
    callToContact: "Llamada de apoyo",
    callToContactNamed: "Llamada de apoyo a",

    genericError: "Algo salió mal. Inténtalo de nuevo.",
  },
}

export type V2Strings = (typeof V2_STRINGS)["en"]
